import { defineField, defineType } from "sanity";

export default defineType({
  name: "profile",
  title: "Profile & Settings",
  type: "document",
  groups: [
    { name: "general", title: "General & Branding" },
    { name: "hero", title: "Hero Section" },
    { name: "about", title: "About Section" },
    { name: "contact", title: "Contact & Footer" },
  ],
  fields: [
    defineField({
      name: "name",
      title: "Full Name",
      type: "string",
      group: "general",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "wordmarkGhost",
      title: "Wordmark Ghost Initial (e.g. 'A')",
      type: "string",
      group: "general",
      initialValue: "A",
    }),
    defineField({
      name: "wordmarkRest",
      title: "Wordmark Rest of Name (e.g. 'bhiram.')",
      type: "string",
      group: "general",
      initialValue: "bhiram.",
    }),
    defineField({
      name: "title",
      title: "Professional Subtitle (e.g. Frontend Developer)",
      type: "string",
      group: "general",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "headlineWord1",
      title: "Hero Headline Line 1",
      type: "string",
      group: "hero",
      initialValue: "ENGINEERING",
    }),
    defineField({
      name: "headlineWord2",
      title: "Hero Headline Line 2",
      type: "string",
      group: "hero",
      initialValue: "THE FUTURE",
    }),
    defineField({
      name: "estText",
      title: "Experience Badge Text (e.g. Frontend Developer · 2+ Years)",
      type: "string",
      group: "hero",
    }),
    defineField({
      name: "heroLede",
      title: "Hero Intro Lede Paragraph",
      type: "text",
      group: "hero",
    }),
    defineField({
      name: "disciplines",
      title: "Disciplines List (e.g. React.js, Next.js, TypeScript)",
      type: "array",
      group: "hero",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "heroRole",
      title: "Hero Role Tag (e.g. Frontend Developer)",
      type: "string",
      group: "hero",
    }),
    defineField({
      name: "image",
      title: "Profile / Hero Portrait Image",
      type: "image",
      group: "hero",
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: "resume",
      title: "Resume / CV File",
      type: "file",
      group: "hero",
    }),
    defineField({
      name: "bio1",
      title: "About Bio / Quote",
      type: "text",
      group: "about",
      description: "Main bio text displayed in the About section.",
    }),
    defineField({
      name: "stats",
      title: "Statistics Numbers",
      type: "array",
      group: "about",
      of: [
        {
          type: "object",
          fields: [
            { name: "value", type: "string", title: "Value (e.g., 2)" },
            { name: "suffix", type: "string", title: "Suffix (e.g., +)" },
            { name: "label", type: "string", title: "Label (e.g., Years Experience)" },
          ],
        },
      ],
    }),
    defineField({
      name: "email",
      title: "Email",
      type: "string",
      group: "contact",
    }),
    defineField({
      name: "mobile",
      title: "Mobile / WhatsApp Number",
      type: "string",
      group: "contact",
    }),
    defineField({
      name: "linkedin",
      title: "LinkedIn URL",
      type: "url",
      group: "contact",
    }),
    defineField({
      name: "github",
      title: "GitHub URL",
      type: "url",
      group: "contact",
    }),
    defineField({
      name: "location",
      title: "Location",
      type: "string",
      group: "contact",
    }),
    defineField({
      name: "availabilityStatus",
      title: "Availability Status (e.g. Open to Opportunities)",
      type: "string",
      group: "contact",
    }),
    defineField({
      name: "availabilityLocation",
      title: "Availability Location (e.g. Kottayam, Kerala, India)",
      type: "string",
      group: "contact",
    }),
    defineField({
      name: "scatterKeywords",
      title: "Contact Section Ambient Keywords",
      type: "array",
      group: "contact",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "channels",
      title: "Contact Channels & Bento Cards",
      type: "array",
      group: "contact",
      of: [
        {
          type: "object",
          fields: [
            {
              name: "type",
              type: "string",
              title: "Icon Selector",
              description: "Select the icon & branding to display on this card",
              options: {
                list: [
                  { title: "WhatsApp", value: "whatsapp" },
                  { title: "LinkedIn", value: "linkedin" },
                  { title: "GitHub", value: "github" },
                  { title: "X (formerly Twitter)", value: "x" },
                  { title: "Instagram", value: "instagram" },
                  { title: "Pinterest", value: "pinterest" },
                  { title: "YouTube", value: "youtube" },
                  { title: "Email", value: "email" },
                  { title: "Custom / Generic Link", value: "custom" },
                ],
                layout: "dropdown",
              },
              initialValue: "custom",
            },
            { name: "label", type: "string", title: "Label" },
            { name: "value", type: "string", title: "Direct Value (e.g. email or phone)" },
            { name: "displayValue", type: "string", title: "Display Text" },
            { name: "tag", type: "string", title: "Badge Tag" },
            { name: "title", type: "string", title: "Card Title" },
            { name: "description", type: "string", title: "Card Description" },
            { name: "href", type: "string", title: "Action Link URL" },
            { name: "actionLabel", type: "string", title: "Action Button Text" },
            { name: "featured", type: "boolean", title: "Featured Spotlight (e.g. Email Card)" },
          ],
        },
      ],
    }),
    defineField({
      name: "legalCopyright",
      title: "Legal Copyright Text",
      type: "string",
      group: "contact",
    }),
    defineField({
      name: "legalCredit",
      title: "Legal Credit Text",
      type: "string",
      group: "contact",
    }),
  ],
});
