name: Deploy Portfolio to GitHub Pages Repo

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Portfolio Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js
        run: |
          npm run build

      - name: Clone GitHub Pages Repo
        run: |
          git clone --branch master https://x-access-token:${{ secrets.GH_PAGES_TOKEN }}@github.com/Abhi-raam/Abhi-raam.github.io.git pages

      - name: Remove Old Files
        run: |
          find pages -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

      - name: Copy Exported Site
        run: |
          cp -r out/* pages/

      - name: Commit and Push
        run: |
          cd pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "Deploy from portfolio repo" || echo "No changes"

          git push